**Assignment 1 Submission (by Daniel Kim and Hikma Awol)**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

import pandas as pd
df = pd.read_csv('ToyotaC

In [104]:
import keras
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

X = pd.DataFrame(np.c_[df['Price'], df['Age_08_04'], df['KM'],
df['Fuel_Type'], df['HP'], df['Automatic'],
df['Doors'], df['Quarterly_Tax'], df['Mfr_Guarantee'],
df['Guarantee_Period'], df['Airco'],
df['Automatic_airco'], df['CD_Player'],
df['Powered_Windows'], df['Sport_Model'],
df['Tow_Bar']], columns = ['Price', 'Age_08_04', 'KM', 'Fuel_Type', 'HP',
'Automatic', 'Doors', 'Quarterly_Tax', 'Mfr_Guarantee',
'Guarantee_Period', 'Airco', 'Automatic_airco', 'CD_Player',
'Powered_Windows', 'Sport_Model', 'Tow_Bar'])
# X = X.values
# y = Y.values


In [45]:
X.iloc[1:10, 3]

1    Diesel
2    Diesel
3    Diesel
4    Diesel
5    Diesel
6    Diesel
7    Diesel
8    Petrol
9    Diesel
Name: Fuel_Type, dtype: object

In [87]:
print("doors: ", X['Doors'].unique())
print("Fuel_Type: ", X['Fuel_Type'].unique())


doors:  [3 5 4 2]
Fuel_Type:  ['Diesel' 'Petrol' 'CNG']


In [105]:
# Doors column
ct2 = ColumnTransformer([("Fuel_Type", OneHotEncoder(), [3]),("Doors", OneHotEncoder(), [6])], remainder = 'passthrough')
X_new = ct2.fit_transform(X)
X_new[0:10,]


array([[0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 13500, 23, 46986, 90, 0, 210,
        0, 3, 0, 0, 0, 1, 0, 0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 13750, 23, 72937, 90, 0, 210,
        0, 3, 1, 0, 1, 0, 0, 0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 13950, 24, 41711, 90, 0, 210,
        1, 3, 0, 0, 0, 0, 0, 0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 14950, 26, 48000, 90, 0, 210,
        1, 3, 0, 0, 0, 0, 0, 0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 13750, 30, 38500, 90, 0, 210,
        1, 3, 1, 0, 0, 1, 0, 0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 12950, 32, 61000, 90, 0, 210,
        0, 3, 1, 0, 0, 1, 0, 0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 16900, 27, 94612, 90, 0, 210,
        0, 3, 1, 0, 0, 1, 1, 0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 18600, 30, 75889, 90, 0, 210,
        1, 3, 1, 0, 1, 1, 0, 0],
       [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 21500, 27, 19700, 192, 0, 100,
        0, 3, 1, 0, 0, 1, 0, 0],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 12

In [106]:
#scaling
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X_normalized = mms.fit_transform(X_new)
X_normalized[0][:]

array([0.        , 1.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.3250444 , 0.27848101, 0.19335471,
       0.17073171, 0.        , 0.72348485, 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        ])

In [58]:
X_normalized[0][[1,7]]

array([1.       , 0.3250444])

In [107]:
#Split the data into test and training set
from sklearn.model_selection import train_test_split
# Split Price column from the other variables
X_normalized = X_normalized[:, [0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19]] 
price = X_normalized[:, 7]

X_train, X_test, y_train, y_test = train_test_split(X_normalized, price, test_size =0.3, random_state = 0)


In [93]:
shape = X_normalized.shape
shape

(1436, 19)

In [94]:
price

array([0.19335471, 0.30014938, 0.1716468 , ..., 0.07002086, 0.06960934,
       0.        ])

In [108]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense


# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 2, kernel_initializer = 'uniform',activation = 'relu', input_dim = shape[1]))


# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = keras.losses.MeanSquaredError(), metrics = [keras.metrics.RootMeanSquaredError()])



# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 20)
classifier.summary()

Epoch 1/20
101/101 [==============================] - 1s 846us/step - loss: 0.4711 - root_mean_squared_error: 0.6858
Epoch 2/20
101/101 [==============================] - 0s 908us/step - loss: 0.1467 - root_mean_squared_error: 0.3808
Epoch 3/20
101/101 [==============================] - 0s 870us/step - loss: 0.0652 - root_mean_squared_error: 0.2552
Epoch 4/20
101/101 [==============================] - 0s 822us/step - loss: 0.0453 - root_mean_squared_error: 0.2127
Epoch 5/20
101/101 [==============================] - 0s 956us/step - loss: 0.0294 - root_mean_squared_error: 0.1713
Epoch 6/20
101/101 [==============================] - 0s 869us/step - loss: 0.0226 - root_mean_squared_error: 0.1503
Epoch 7/20
101/101 [==============================] - 0s 885us/step - loss: 0.0180 - root_mean_squared_error: 0.1340
Epoch 8/20
101/101 [==============================] - 0s 948us/step - loss: 0.0157 - root_mean_squared_error: 0.1252
Epoch 9/20
101/101 [==============================] - 0s 861us/s

In [109]:
y_pred = classifier.predict(X_test)

In [111]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rms_test = sqrt(mean_squared_error(y_test, y_pred))
print("RMS Error for training model with 1 layer and 2 nodes is .073 on 20th epoch")

rms_test = sqrt(mean_squared_error(y_test, y_pred))

print("RMS Error for test model with 1 layer and 2 nodes is", rms_test)

RMS Error for training model with 1 layer and 2 nodes is .073 on 20th epoch
RMS Error for test model with 1 layer and 2 nodes is 0.0686864376756383


**For single layer with 5 nodes**


In [112]:
# Initialising the ANN
five_node_model = Sequential()

# Adding the input layer and the first hidden layer
five_node_model.add(Dense(units = 5, kernel_initializer = 'uniform',activation = 'relu', input_dim = shape[1]))

# Adding the output layer
five_node_model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))

# Compiling the ANN
five_node_model.compile(optimizer = 'adam', loss = keras.losses.MeanSquaredError(), metrics = [keras.metrics.RootMeanSquaredError()])

# Fitting the ANN to the Training set
five_node_model.fit(X_train, y_train, batch_size = 10, epochs = 20)


Epoch 1/20
101/101 [==============================] - 0s 1ms/step - loss: 0.4631 - root_mean_squared_error: 0.6794
Epoch 2/20
101/101 [==============================] - 0s 987us/step - loss: 0.1012 - root_mean_squared_error: 0.3174
Epoch 3/20
101/101 [==============================] - 0s 965us/step - loss: 0.0542 - root_mean_squared_error: 0.2326
Epoch 4/20
101/101 [==============================] - 0s 946us/step - loss: 0.0382 - root_mean_squared_error: 0.1951
Epoch 5/20
101/101 [==============================] - 0s 1ms/step - loss: 0.0237 - root_mean_squared_error: 0.1539
Epoch 6/20
101/101 [==============================] - 0s 1ms/step - loss: 0.0175 - root_mean_squared_error: 0.1323
Epoch 7/20
101/101 [==============================] - 0s 1ms/step - loss: 0.0144 - root_mean_squared_error: 0.1201
Epoch 8/20
101/101 [==============================] - 0s 1ms/step - loss: 0.0134 - root_mean_squared_error: 0.1158
Epoch 9/20
101/101 [==============================] - 0s 1ms/step - loss: 

In [113]:
y_pred = five_node_model.predict(X_test)

In [114]:
print("RMS Error for training model with 1 layer and 5 nodes is .0589 on 20th epoch")

rms_test2 = sqrt(mean_squared_error(y_test, y_pred))

print("RMS Error for test model with 1 layer and 2 nodes is", rms_test2)

RMS Error for training model with 1 layer and 5 nodes is .0589 on 20th epoch
RMS Error for test model with 1 layer and 2 nodes is 0.055282418583948126


**2 layers and 5 nodes per Hidden Layer**


In [118]:
# Initialising the ANN
two_layer_five_node_model = Sequential()

# Adding the input layer and the first hidden layer
two_layer_five_node_model.add(Dense(units = 5, kernel_initializer = 'uniform',activation = 'relu', input_dim = shape[1]))

# Adding the input layer and the first hidden layer
two_layer_five_node_model.add(Dense(units = 5, kernel_initializer = 'uniform',activation = 'relu'))

# Adding the output layer
two_layer_five_node_model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))

# Compiling the ANN
two_layer_five_node_model.compile(optimizer = 'adam', loss = keras.losses.MeanSquaredError(), metrics = [keras.metrics.RootMeanSquaredError()])

# Fitting the ANN to the Training set
two_layer_five_node_model.fit(X_train, y_train, batch_size = 10, epochs = 20)

Epoch 1/20
101/101 [==============================] - 0s 1ms/step - loss: 0.4890 - root_mean_squared_error: 0.6984
Epoch 2/20
101/101 [==============================] - 0s 1ms/step - loss: 0.1178 - root_mean_squared_error: 0.3403
Epoch 3/20
101/101 [==============================] - 0s 1ms/step - loss: 0.0441 - root_mean_squared_error: 0.2098
Epoch 4/20
101/101 [==============================] - 0s 1ms/step - loss: 0.0286 - root_mean_squared_error: 0.1689
Epoch 5/20
101/101 [==============================] - 0s 1ms/step - loss: 0.0181 - root_mean_squared_error: 0.1344
Epoch 6/20
101/101 [==============================] - 0s 1ms/step - loss: 0.0140 - root_mean_squared_error: 0.1180
Epoch 7/20
101/101 [==============================] - 0s 1ms/step - loss: 0.0135 - root_mean_squared_error: 0.1161
Epoch 8/20
101/101 [==============================] - 0s 1ms/step - loss: 0.0113 - root_mean_squared_error: 0.1064
Epoch 9/20
101/101 [==============================] - 0s 1ms/step - loss: 0.0099

In [119]:
y_pred = two_layer_five_node_model.predict(X_test)

In [120]:
print("RMS Error for training model with 1 layer and 5 nodes is .0232 on 20th epoch")

rms_test3 = sqrt(mean_squared_error(y_test, y_pred))

print("RMS Error for test model with 1 layer and 2 nodes is", rms_test3)

RMS Error for training model with 1 layer and 5 nodes is .0232 on 20th epoch
RMS Error for test model with 1 layer and 2 nodes is 0.034892163345145485


**What happens to the RMS error for the training data as the number of layers
and nodes increases?**



The RMS error decreased when the nodes were increased and the last model with two hidden layers and 5 nodes each actually did the best out of all three models. 

**What happens to the RMS error for the validation data?**


the RMS decreased for the testing dataset for the first two models (1 layer and 2 nodes, 1 layer and 5 nodes). But the last model with two hidden layers had a higher RMS Error for Validation versus the training. 

**Comment on the appropriate number of layers and nodes for this application.**

Based on our results we believe the 2 hidden layers with 5 nodes each model is the best because it had the least RMS Error.